### ISSUE TITLE
all fields of type set/list with exactly 1 element must have the MaxItemsOne property

### ISSUE THREAD

**Issue by ocobleseqx** [equinix/pulumi-equinix#5]
In terraform, fields that have a nested schema are defined with type Set/List, but they just have exactly 1 nested element, so for example the [equinix_fabric_connection.redundancy](https://registry.terraform.io/providers/equinix/equinix/latest/docs/resources/equinix_fabric_connection#nested-schema-for-redundancy) is a single field with a nested schema with the property [priority](https://registry.terraform.io/providers/equinix/equinix/latest/docs/resources/equinix_fabric_connection#priority). It can be defined this way:

```
resource "equinix_fabric_connection" "example" {
    ...
    redundancy {priority= "PRIMARY"}
    ...
}
```

However, in Pulumi, if not specified in the provider definition in resources.go with the property `MaxItemsOne`, they are added in the schema with a key in plural and it expects an array in the configuration. 

```
resources:
  example:
    type: equinix:fabric:Connection
    properties:
      redundancies:
      - priority: PRIMARY
```

Adding the `MaxItemsOne` it will be:

```
resources:
  example:
    type: equinix:fabric:Connection
    properties:
      redundancy:
        priority: PRIMARY
```

All items with nested attributes must be updated
